### Code for CodeDataService and CanvasDataService
### Each Canvas is associated with a table
import psycopg2
from psycopg2 import sql


class CodeDataService:
    """
    Service to connect to a canvas' postgres table to edit its codes' data
    """

    _columns: list[str] = ["id", "codeid", "collection", "text", "color", "position", "background_color", "border_color"]
    _text_columns: list[str] = ["collection", "text", "background_color", "border_color"]

    @staticmethod
    def _format_value(entry: str, value):
        if entry == "position":
            x, y = value
            return f"({float(x)},{float(y)})"
        return value

    def __init__(self, canvas_name: str = None):
        """
        Initialize a CodeDataService instance to connect to a canvas' postgres database
        # Parameters
            canvas_name (str): The name of the canvas
        # Raises
            TypeError if canvas_name is None
            ValueError if canvas_name is a whitespace string
        """

        if canvas_name is None:
            raise TypeError("table_name for CodeDataService cannot be of type None")
        if canvas_name.strip() == "":
            raise ValueError("canvas_name is a whitespace string")

        self.canvas_name = canvas_name

    def __enter__(self):

        try:
            self.conn = psycopg2.connect(
                dbname="dev_db",
                user="dev",
                password="12345",
                host="localhost",
                port="5432",
                connect_timeout=5,
            )
        except Exception as e:
            print(e)
            raise ConnectionError(
                "Could not connect to PostgreSQL. Start the Postgres service, "
                "then ensure database dev_db exists for user dev (password in docker/development.yml)."
            ) from e

        self.cur = self.conn.cursor()

        self.cur.execute(sql.SQL("""CREATE TABLE IF NOT EXISTS {} (
                         id SERIAL PRIMARY KEY,
                         codeid BIGINT UNIQUE,
                         collection VARCHAR(100),
                         text VARCHAR(1000),
                         color INT,
                         position POINT,
                         background_color VARCHAR(20),
                         border_color VARCHAR(20)
                         );
                         """).format(sql.Identifier(self.canvas_name)))
        self.cur.execute(sql.SQL("""ALTER TABLE {}
                         ALTER COLUMN codeid TYPE BIGINT;
                         """).format(sql.Identifier(self.canvas_name)))

        self.cur.execute(sql.SQL("""
            ALTER TABLE {}
            ADD COLUMN IF NOT EXISTS background_color VARCHAR(20);
        """).format(sql.Identifier(self.canvas_name)))

        self.cur.execute(sql.SQL("""
            ALTER TABLE {}
            ADD COLUMN IF NOT EXISTS border_color VARCHAR(20);
        """).format(sql.Identifier(self.canvas_name)))

        return self

    def __exit__(self, exc_type, exc, tb):
        if getattr(self, "conn", None) is None:
            return False
        self.conn.commit()
        self.cur.close()
        self.conn.close()
        return False

    def create_code_entry(self, **kwargs) -> int:
        """
        Creates a new code entry based on the provided information passed through kwargs
        # Parameters
            A kwargs dictionary with the following entries:
                codeid (int): (Mandatory) A unique id generated by the frontend to more easily track codes
                collection (str): (Optional) A string containing the collection the code is a part of
                text (str): (Optional) The text that the code contains
                position (tuple[float, float]): (Optional) The position the code is on the canvas
                color (int): (Optional) The color of the code, currently an int for hard-coded colors
        # Raises
            KeyError if codeid is not in kwargs
        # Returns
            The database id for the code
        """

        if "codeid" not in kwargs.keys():
            raise KeyError("codeid missing")

        entries = [entry for entry in kwargs if entry in self._columns]
        values = [
            self._format_value(entry, kwargs[entry])
            for entry in entries
        ]

        self.cur.execute(
            sql.SQL("INSERT INTO {} ({}) VALUES ({});").format(
                sql.Identifier(self.canvas_name),
                sql.SQL(", ").join(map(sql.Identifier, entries)),
                sql.SQL(", ").join(sql.Placeholder() for _ in entries),
            ),
            values,
        )

        self.cur.execute(
            sql.SQL("SELECT * FROM {} WHERE codeid = %s;").format(
                sql.Identifier(self.canvas_name)
            ),
            (kwargs["codeid"],),
        )
        
        return self.cur.fetchone()[0]

    def delete_code_entry(self, codeid: int = None):
        """
        Deletes a code entry from the canvas' database
        # Parameters
            codeid (int): The codeid of the code to delete
        # Raises
            TypeError if codeid is None
        """

        if codeid is None:
            TypeError("codeid is of type None")

        self.cur.execute(
            sql.SQL("DELETE FROM {} WHERE codeid = %s;").format(
                sql.Identifier(self.canvas_name)
            ),
            (codeid,),
        )

    def update_code_entry(self, **kwargs):
        """
        Updates a code based on the provided codeid
        # Parameters
            A kwargs dictionary with the following entries:
                codeid (int): (Mandatory) A unique id generated by the frontend to more easily track codes
                collection (str): (Optional) A string containing the collection the code is a part of
                text (str): (Optional) The text that the code contains
                position (tuple[float, float]): (Optional) The position the code is on the canvas
                color (int): (Optional) The color of the code, currently an int for hard-coded colors
        # Raises
            KeyError if codeid is not in kwargs
        """

        if "codeid" not in kwargs.keys():
            raise KeyError("codeid missing")

        # Generate the SET clause dynamically based on the provided data.
        assignments = []
        values = []
        for entry in kwargs:
            if entry in self._columns and entry not in ["id", "codeid"]:
                assignments.append(
                    sql.SQL("{} = %s").format(sql.Identifier(entry))
                )
                values.append(self._format_value(entry, kwargs[entry]))

        if not assignments:
            return

        values.append(kwargs["codeid"])

        self.cur.execute(
            sql.SQL("UPDATE {} SET {} WHERE codeid = %s;").format(
                sql.Identifier(self.canvas_name),
                sql.SQL(", ").join(assignments),
            ),
            values,
        )

    def get_code_by_id(self, id: int = None) -> tuple | None:
        """
        Returns the code associated with the provided database id
        # Parameters
            id (int): The database id
        # Raises
            TypeError if id is None
            ValueError if id < 0
        # Returns
            A tuple containing the information of retrieved code or None if no code with the provided was found
        # Note
            The tuple is of the following format:
                (id, codeid, collection, text, color, position)
        """

        if id is None:
            raise TypeError("id is None")
        if id is not None:
            if id < 0:
                raise ValueError("Invalid id")

        self.cur.execute(
            sql.SQL("SELECT * FROM {} WHERE id = %s;").format(
                sql.Identifier(self.canvas_name)
            ),
            (id,),
        )
        return self.cur.fetchall()

    def get_code_by_codeid(self, codeid: int = None) -> tuple | None:
        """
        Returns the code associated with the provided codeid
        # Parameters
            codeid (int): The codeid
        # Raises
            TypeError if codeid is None
        # Returns
            A tuple containing the information of retrieved code or None if no code with the provided was found
        # Note
            The tuple is of the following format:
                (id, codeid, collection, text, color, position)
        """

        if codeid is None:
            raise TypeError("codeid is None")

        self.cur.execute(
            sql.SQL("SELECT * FROM {} WHERE codeid = %s;").format(
                sql.Identifier(self.canvas_name)
            ),
            (codeid,),
        )
        return self.cur.fetchall()
    
    def get_max_codeid(self) -> int | None:
        """
        Gets the highest codeid value found in the canvas' postgres database
        # Returns
            An int representing the highest codeid found or None if no entries with a codeid exist
        """

        # https://stackoverflow.com/questions/4910790/how-do-i-find-the-largest-value-in-a-column-in-postgres-sql
        self.cur.execute(sql.SQL("""SELECT codeid
                         FROM {}
                         ORDER BY codeid
                         DESC
                         LIMIT 1;""").format(sql.Identifier(self.canvas_name)))
        row = self.cur.fetchone()
        return row[0] if row else None

    def get_collections(self) -> list | None:
        """
        Gets all collections found within the canvas' postgres database
        # Returns
            A list containing the names of all the collections
        # Note
            If any code does not belong to a collection, None will appear as a collection
            It is possible to have [None] if no collections exist
        """
        self.cur.execute(
            sql.SQL("SELECT DISTINCT collection FROM {};").format(
                sql.Identifier(self.canvas_name)
            )
        )
        return [c[0] for c in self.cur.fetchall()]

    def get_collection_counts(self) -> list[tuple[str, int]]:
        """
        Returns (group_name, note_count) pairs for the current canvas.
        NULL collections are treated as 'default'.
        """
        self.cur.execute(
            sql.SQL(
                """
                SELECT COALESCE(collection, 'default') AS grp, COUNT(*)::int
                FROM {}
                GROUP BY COALESCE(collection, 'default')
                ORDER BY grp;
                """
            ).format(sql.Identifier(self.canvas_name))
        )
        return [(row[0], row[1]) for row in self.cur.fetchall()]

    def fetch_codes(self) -> list[tuple]:
        """
        Gets all codes found within the canvas' postgres database
        # Returns
            A list of tuples where each tuple corresponds to a code entry
        # Note
            The tuple is of the following format:
                (id, codeid, collection, text, color, position)
        """
        self.cur.execute(
            sql.SQL("SELECT * FROM {}").format(sql.Identifier(self.canvas_name))
        )
        return self.cur.fetchall()
    
    def delete_canvas_table(self):
        """
        Deletes the canvas' associated postgres database
        """
        self.cur.execute(
            sql.SQL("DROP TABLE {}").format(sql.Identifier(self.canvas_name))
        )


class CanvasDataService:
    """
    Service to connect to the Postgres database containing information on all canvases
    """

    def __init__(self):
        pass

    def __enter__(self):

        try:
            self.conn = psycopg2.connect(
                dbname="dev_db",
                user="dev",
                password="12345",
                host="localhost",
                port="5432",
                connect_timeout=5,
            )
        except Exception as e:
            print(e)
            raise ConnectionError(
                "Could not connect to PostgreSQL. Start the Postgres service, "
                "then ensure database dev_db exists for user dev (password in docker/development.yml)."
            ) from e

        self.cur = self.conn.cursor()

        self.cur.execute("""CREATE TABLE IF NOT EXISTS canvas (
                         id SERIAL PRIMARY KEY,
                         name VARCHAR(50) UNIQUE
                         );
                         """)
        return self

    def __exit__(self, exc_type, exc, tb):
        if getattr(self, "conn", None) is None:
            return False
        self.conn.commit()
        self.cur.close()
        self.conn.close()
        return False

    def create_canvas(self, canvas_name: str = None) -> int:
        """
        Create an entry into the canvas Postgres database with name `canvas_name`
        # Parameters
            canvas_name (str): The name of the canvas
        # Raises
            TypeError if canvas_name is None.
            ValueError if canvas_name is a whitespace string
        # Returns
            An int corresponding to the canvases id in the Postgres database
        """

        if canvas_name is None:
            raise TypeError("canvas_name cannot be None in create_canvas")
        elif canvas_name.strip() == "":
            raise ValueError("canvas_name cannot be an empty or whitespace string")

        cleaned_name = canvas_name.strip()

        self.cur.execute(
            "INSERT INTO canvas (name) VALUES (%s);",
            (cleaned_name,),
        )

        self.cur.execute(
            "SELECT * FROM canvas WHERE name = %s;",
            (cleaned_name,),
        )
        
        return self.cur.fetchone()[0]

    def fetch_canvases(self) -> list[tuple[int, str]]:
        """
        Get a list of canvases in the Postgres database
        # Returns
            A list containing tuple pairs of (database id, name)
        """
        self.cur.execute("""SELECT * FROM canvas""")
        return self.cur.fetchall()
    
    def get_canvas_id(self, canvas_name: str = None) -> int | None:
        """
        Get a canvas' id based on its name
        # Parameters
            canvas_name (str): The name of the canvas
        # Raises
            TypeError if canvas_name is None
            ValueError if canvas_name is a whitespace string
        # Returns
            An int corresponding to the canvas' id in the database or None if no entry with canvas_name was found
        """

        if canvas_name is None:
            raise TypeError("canvas_name is None")
        if canvas_name.strip() == "":
            raise ValueError("Whitespace string given for canvas_name")
        
        self.cur.execute(
            "SELECT id FROM canvas WHERE name = %s;",
            (canvas_name,),
        )

        row = self.cur.fetchone()
        return row[0] if row else None

    def get_canvas_name(self, id: int = None) -> str | None:
        """
        Get a canvas' name based on its id in the Postgres database
        # Parameters
            id (int): The id of the canvas in the Postgres database
        # Raises
            TypeError if id is None
            ValueError if id < 0
        # Returns
            A string corresponding to the name of the canvas with the id or None if no entry with id was found
        """

        if id is None:
            raise TypeError("id is None")
        if id < 0:
            raise ValueError("Incorrect id provided")
        
        self.cur.execute(
            "SELECT name FROM canvas WHERE id = %s;",
            (id,),
        )

        row = self.cur.fetchone()
        return row[0] if row else None

    def delete_canvas(self, canvas_name: str = None, id: int = None):
        """
        Deletes a canvas based on either its name or id in the Postgres database
        # Parameters
            canvas_name (str): The name of the canvas
            id (int): The id of the canvas in the Postgres database
        # Raises
            TypeError if both id and canvas_name are None
            ValueError if an id < 0 is given
            ValueError if a whitespace string is provided for canvas_name
        # Note
            Only the canvas_name or id should be provided, providing both does not change the result
        """

        if id is None and canvas_name is None:
            raise TypeError("id and canvas_name are None")
        if id is not None:
            if id < 0:
                raise ValueError("Incorrect id given in delete_canvas")
        if canvas_name is not None and canvas_name.strip() == "":
            raise ValueError("Whitespace string given for canvas_name")
        
        if id is not None:            
            self.cur.execute("DELETE FROM canvas WHERE id = %s;", (id,))
        elif canvas_name is not None:
            self.cur.execute("DELETE FROM canvas WHERE name = %s;", (canvas_name,))


if __name__ == "__main__":

    with CanvasDataService() as c:
        print(c.delete_canvas("test"))
        print(c.create_canvas("test"))
        print(c.fetch_canvases())
        print(c.get_canvas_id("test"))
        print(c.get_canvas_name(c.get_canvas_id("test")))
        print(c.delete_canvas("test"))
        print(c.fetch_canvases())


    with CanvasDataService() as c:
        print(c.delete_canvas("codetest"))
        print(c.create_canvas("codetest"))

    entry = {
        "text": "This is a test code",
        "color": 0,
        "collection": "Test",
        "position": (2.0, 4.5),
        "codeid": 5,
    }

    update_entry = {
        "text": "This is an updated test code",
        "position": (2.0, 3.5),
        "codeid": 5,
    }

    with CodeDataService(canvas_name="codetest") as codes:
        print(codes.delete_canvas_table())

    with CodeDataService(canvas_name="codetest") as codes:
        print(codes.delete_code_entry(5))
        print(codes.create_code_entry(**entry))
        print(codes.fetch_codes())
        print(codes.update_code_entry(**update_entry))
        print(codes.fetch_codes())
        print(codes.get_code_by_codeid(5))
        print(codes.get_code_by_codeid(1))
        print(codes.get_code_by_id(100))
        print(codes.get_collections())
        print(codes.get_max_codeid())
